stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
      - data/raw/automobile_prices_economics_2019_2023.csv
      - src/preprocess.py
    outs:
      - data/processed/cleaned.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/cleaned.csv
      - src/train.py
    outs:
      - models/model.joblib
    metrics:
      - metrics/scores.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.joblib
      - data/processed/cleaned.csv
    metrics:
      - metrics/evaluation.json
